version: "2"
run:
  modules-download-mode: readonly
  tests: true
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - asasalint
    - copyloopvar
    - durationcheck
    - funlen
    - gocyclo
    - gosec
    - lll
    - misspell
    - prealloc
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 80
      statements: 50
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: early-return
        - name: unexported-return
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - gocyclo
          - lll
        path: _test\.go
      - linters:
          - errcheck
        text: defer .*Close
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 3
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - yourorg
        - github.com/yourorg
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
