run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path-prefix: .

issues:
  max-same-issues: 3
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - lll
    - linters:
        - errcheck
      text: "defer .*Close"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  funlen:
    lines: 80
    statements: 50

  lll:
    line-length: 120
    tab-width: 1

  goimports:
    local-prefixes: yourorg,github.com/yourorg

  revive:
    severity: warning
    rules:
      - name: indent-error-flow
      - name: early-return
      - name: unexported-return

  staticcheck:
    checks: ["all"]

  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - revive
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - misspell
    - gocyclo
    - funlen
    - lll
    - copyloopvar
    - prealloc
    - gosec
    - asasalint
    - durationcheck
